name: build js

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - name: Check differences
    - run: echo "::set-env name=DIFF::$(git diff)"
    - name: Commit report
      if: env.DIFF
      run: |
          git config --global user.name 'joonas-bot'
          git config --global user.email 'joonas-yoon@users.noreply.github.com'
          git add -A
          git commit -m "bot: build by github action"
          git push